### ISSUE TITLE
0.9.3 reporting as 0.9.2 once installed

### ISSUE THREAD

**Issue by Efus10n** [chof747/octoprint-autoprint#11]
Using Octoprint, got the update notification. It seems to install correctly, but still reports as 0.9.2 once it's installed which causes Octoprint to keep notifying me of the update. 

Thought it was an install failure but second attempt the log shows it already had the same version already installed.

Could it be because [setup.py](https://github.com/chof747/octoprint-autoprint/blob/master/setup.py#L17) still lists plugin_version = "0.9.2" ?

`Looks like we were already installed in this version. Forcing a reinstall.
/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/chof747/octoprint-autoprint/archive/0.9.3.zip --no-cache-dir --ignore-installed --force-reinstall --no-deps
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/chof747/octoprint-autoprint/archive/0.9.3.zip
Downloading https://github.com/chof747/octoprint-autoprint/archive/0.9.3.zip
Building wheels for collected packages: OctoPrint-Autoprint
Building wheel for OctoPrint-Autoprint (setup.py): started
Building wheel for OctoPrint-Autoprint (setup.py): finished with status 'done'
Created wheel for OctoPrint-Autoprint: filename=OctoPrint_Autoprint-0.9.2-py2.py3-none-any.whl size=13777 sha256=93e2a4264a172084e27d377bfcb94c17e6546cd67a0efade6f4ba85b4200652f
Stored in directory: /tmp/pip-ephem-wheel-cache-drq1m581/wheels/02/dc/bb/742c32bc7eebe6058cb8588c492efff309738c699bf1cd8c31
Successfully built OctoPrint-Autoprint
Installing collected packages: OctoPrint-Autoprint
Successfully installed OctoPrint-Autoprint-0.9.2
The update finished successfully and the server will now be restarted.`

**Comment by chof747** [comment]
Fixed it and changed the version to 0.9.4 in setup.py and the and merged the branch.
