### ISSUE TITLE
Use Octoprint file browser to select files for autoprinting

### ISSUE THREAD

**Issue by chof747** [chof747/octoprint-autoprint#9]
After enabling printing from every file location the idea is to use the OctoPrint file browser to select the files more conveniently.
(as suggested in #8 by @au-mikey

**Comment by chof747** [comment]
The solution was implemented via additional mini icons in the file browser (credit to @jneilliii in here [
Use FileBrowser in sidebar to select a file for a plugin tab](https://community.octoprint.org/t/use-filebrowser-in-sidebar-to-select-a-file-for-a-plugin-tab/45991/3?u=chof).

When selecting a file via this mini button it is now entered into  the comboboxes and scheduling an autostart can be done as if the combos had been used for selecting the file.

@au-mikey would you like to test this new functionality by installing the version of the specific dev branch (https://github.com/chof747/octoprint-autoprint/archive/refs/heads/9-use-octoprint-file-browser.zip)?

**Comment by au-mikey** [comment]
Tested the new features. Everything appears to be working as designed.
